[platformio]
name = Bekant
description = ESP32 mod for the IKEA Bekant desk featuring the Megadesk replacement controller
core_dir = .platformio

[env]
framework = arduino
monitor_speed = 115200

[avr]
platform = platformio/atmelavr @ 5.3.0
platform_packages =
	platformio/framework-arduino-avr-attiny @ 1.5.2
	platformio/tool-avrdude @ 1.80100.0
	platformio/toolchain-atmelavr @ 3.70300.220127
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
monitor_filters =
	direct
	log2file
	time
upload_protocol = custom
upload_flags =
    -carduino
    -P$UPLOAD_PORT
upload_command = avrdude $UPLOAD_FLAGS -p$BOARD_MCU -C${platformio.packages_dir}/tool-avrdude/avrdude.conf -Uflash:w:$SOURCE:i
upload_port = net:bekant.local:328 ; Upload via the ESP32

[env:attiny841]
extends = avr
board = attiny841
board_fuses.lfuse = 0xE2
board_fuses.efuse = 0xFE
board_fuses.hfuse = 0xD6
board_fuses.lock_bits = 0xFF

[esp32]
platform = https://api.github.com/repos/pioarduino/platform-espressif32/tarball/2024.07.00 ; 2024.07.00
lib_deps =
	bblanchon/ArduinoJson @ 7.4.3
	bertmelis/espMqttClient @ 1.7.3
	makuna/NeoPixelBus @ 2.8.4
build_flags =
	-DCONFIG_ARDUHAL_LOG_COLORS
	-DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO ; NONE, ERROR, WARN, INFO, DEBUG, VERBOSE
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
monitor_filters =
	esp32_exception_decoder
	log2file
	time
;upload_protocol = espota
;upload_port = bekant.local
;upload_flags = --auth="password"

[env:esp32-c6-zero-b]
extends = esp32
board = esp32-c6-devkitm-1
board_build.partitions = min_spiffs.csv
