name: Clang

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  context:
    name: PlatformIO context
    uses: ./.github/context.yml

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Clang format
        uses: cpp-linter/cpp-linter-action@dacf512996b9cfe9d9bcc7b326d1f3a64ab7b91f # v2.22.0
        id: format
        with:
          files-changed-only: false
          step-summary: true
          style: file
          tidy-checks: -*

      - name: Summary
        run: |
          echo "Clang report:"
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}?pr=${{ github.event.pull_request.number }}"
          else
            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          fi
          exit $(( ${{ steps.format.outputs.clang-format-checks-failed }} != 0 ))

  tidy:
    name: Tidy
    needs: context
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ${{ fromJSON(needs.platformio.outputs.environments) }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Restore Cache for PlatformIO
        continue-on-error: true
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: ${{ needs.context.outputs.pio-cache }}
          path: .platformio/.cache

      - name: Set up uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          python-version: 3.11
          version: latest-known

      - name: PlatformIO compilation database
        env:
          PIO_ENVIRONMENT: ${{ matrix.environment }}
        run: |
          cat <<'EOL' > include/esp/secrets.h
          #pragma once
          #ifdef ARDUINO_ARCH_ESP32
          #define HOSTNAME "bekant"
          #define MQTT_HOST "localhost"
          #define MQTT_KEY "redacted"
          #define MQTT_USER "redacted"
          #define NAME "Bekant"
          #define OTA_KEY "redacted"
          #define PIN_ADC 1
          #define PIN_LED 2
          #define PIN_MISO 3
          #define PIN_MOSI 4
          #define PIN_OE 5
          #define PIN_RST 6
          #define PIN_SCK 7
          #define PIN_TPDN 8
          #define PIN_TPUP 9
          #define WIFI_KEY "redacted"
          #define WIFI_SSID "redacted"
          #endif // ARDUINO_ARCH_ESP32
          EOL
          uv run pio run -t compiledb -e "$PIO_ENVIRONMENT"

      - name: Clang tidy
        uses: cpp-linter/cpp-linter-action@dacf512996b9cfe9d9bcc7b326d1f3a64ab7b91f # v2.22.0
        id: tidy
        with:
          extra-args: -DCORE_DEBUG_LEVEL=5
          file-annotations: false
          files-changed-only: false
          step-summary: true
          style: ""
          tidy-checks: ""

      - name: Summary
        env:
          clang-threshold: 4
        run: |
          echo "Status: ${{ steps.tidy.outputs.checks-failed }} checks failed, threshold for success is ${{ env.clang-threshold }}."
          echo "Clang report:"
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}?pr=${{ github.event.pull_request.number }}"
          else
            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          fi
          exit $(( ${{ steps.tidy.outputs.checks-failed }} > ${{ env.clang-threshold }} ))
